[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
    { access = "read-write", path = "./" }
    
]

[rpc_endpoints]
zksync_local   = "http://127.0.0.1:3050"
zksync_testnet = "https://sepolia.era.zksync.dev"
zksync_mainnet = "https://mainnet.era.zksync.io"

[profile.default.zksync]
optimizer = true
optimizer_runs = 200

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'murky/=lib/murky/'
]
